version: "3"
services:
  app:
    image: forecast
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg:
